name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pytest requests playwright pytest-playwright
          playwright install chromium

      - name: Run pytest tests
        run: pytest python-pytest/ api-tests/

      - name: Run Playwright tests
        run: pytest ui-tests/